### ISSUE TITLE
String.length() 접근할 때 NullPointerException이 뜹니다

### ISSUE THREAD

**Issue by jis1218** [shineware/komoran-tokenizer#1]
Kibana Dev Tools를 이용하여 elasticsearch_examples.txt의 Index Setting을 그대로 돌렸는데
다음과 같은 에러가 뜹니다.

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "null_pointer_exception",
        "reason" : "Cannot invoke \"String.length()\" because \"str\" is null"
      }
    ],
    "type" : "null_pointer_exception",
    "reason" : "Cannot invoke \"String.length()\" because \"str\" is null"
  },
  "status" : 500
}
```

도와주십시오 ㅜ.ㅜ

**Comment by shin285** [comment]
안녕하세요. 혹시 https://github.com/shineware/KOMORAN/tree/master/elasticsearch-plugin 를 사용해서 다시 테스트 해보실 수 있을까요? elasticsearch version-up이 되면서 특정 version 이후 부터 empty string에 대한 체크를 진행하고 있어서 위와 같은 에러가 발생하는 것으로 생각됩니다.

**Comment by jis1218** [comment]
> 안녕하세요. 혹시 https://github.com/shineware/KOMORAN/tree/master/elasticsearch-plugin 를 사용해서 다시 테스트 해보실 수 있을까요? elasticsearch version-up이 되면서 특정 version 이후 부터 empty string에 대한 체크를 진행하고 있어서 위와 같은 에러가 발생하는 것으로 생각됩니다.

링크 사용해서 했더니 잘 됩니다. 감사합니다!
